Repository intuit/postcss-themed, pull requests merged in 2020-10, with the labels that each got.

#28 Adding logo
  README.md
  images/logo-negative.png
  images/logo-negative.svg
  images/logo-primary.png
  images/logo-primary.svg
Labels: documentation

#29 chore: added all contributors plugin to auto
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: documentation

#33 Second Logo and Contributors
  .all-contributorsrc
  README.md
  images/logo-animated.gif
Labels: documentation, skip-release

#34 add ability to use a default function for modules
  .all-contributorsrc
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  __tests__/modern.test.ts
  src/index.ts
Labels: hacktoberfest, minor

#36 add theme file to dependencies to get webpack reloading working
  src/index.ts
Labels: minor

#35 refactor: restructure plugin layout for better separation
  __tests__/test-utils.ts
  src/common/index.ts
  src/index.ts
  src/legacy/index.ts
  src/modern/index.ts
  src/types/index.ts
Labels: hacktoberfest, patch
