Repository intuit/postcss-themed, pull requests merged in 2020-09, with the labels that each got.

#11 fix bug where root themes dark mode would be overridden by next theme
  __tests__/modern.test.ts
  __tests__/precedence.test.ts
  src/index.ts
Labels: patch

#13 Force Single Theme in Modern Parser
  README.md
  __tests__/modern.test.ts
  package.json
  src/index.ts
  yarn.lock
Labels: minor

#15 Merge Single Theme
  README.md
  __tests__/modern.test.ts
  __tests__/precedence.test.ts
  src/index.ts
Labels: major

#16 optimizeSingleTheme: Detect missing keys and provide warning.
  src/index.ts
Labels: patch
